import Head from 'next/head'
import { Inter } from 'next/font/google'
import HomeHero from '@/components/HomeHero'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Home Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/editflight-icon.png" />
        </Head>
      <main>
      <HomeHero/>
      </main>
    </>
  )
}
